server:
  port: 1999
  context-path: /
  tomcat:
    uri-encoding: UTF-8

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.0.0.185:3306/smartBox?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 357241689
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml